### ISSUE TITLE
Just ask if I can

### ISSUE THREAD

**Issue by Wabri** [tangledhelix/dotfiles#6]
I use ansible too for my dotfiles and I have create a template repository that might interest you https://github.com/Wabri/Daje

Is it a problem if I see that some of your tasks are interesting and add them to my template repo?

**Comment by tangledhelix** [comment]
I'm fine with that. I should really put license information in that repository, but I haven't. (Partly because a bunch of things in the scripts directory are not things I wrote).

Anyway, I did write all the Ansible roles, you are welcome to copy anything you want from there.

Interesting project, I would probably check it out if mine wasn't already so matured for what I want :)

Dan
